spring:
  redis:
    #连接工厂使用的数据库索引范围0-15
    database: 0
    #地址
    host: 127.0.0.1
    #端口
    port: 6379
    #密码
    password: 123456
    #连接超时
    timeout: 5000
    jedis:
      pool:
        # 最大空闲连接数
        max-idle: 8
        # 最小空闲连接数
        min-idle: 0
        # 获取连接时的最大等待毫秒数(-1阻塞不确定的时间)
        max-wait: -1
        # 最大活跃连接数
        max-active: 8